// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	Event
	EventResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event_EventType int32

const (
	Event_SPAN_BEGIN    Event_EventType = 0
	Event_SPAN_END      Event_EventType = 1
	Event_REQUEST_BEGIN Event_EventType = 2
	Event_REQUEST_END   Event_EventType = 3
)

var Event_EventType_name = map[int32]string{
	0: "SPAN_BEGIN",
	1: "SPAN_END",
	2: "REQUEST_BEGIN",
	3: "REQUEST_END",
}
var Event_EventType_value = map[string]int32{
	"SPAN_BEGIN":    0,
	"SPAN_END":      1,
	"REQUEST_BEGIN": 2,
	"REQUEST_END":   3,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}
func (Event_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Event struct {
	TraceId      string          `protobuf:"bytes,1,opt,name=traceId" json:"traceId,omitempty"`
	SpanId       string          `protobuf:"bytes,2,opt,name=spanId" json:"spanId,omitempty"`
	ParentSpanId string          `protobuf:"bytes,3,opt,name=parentSpanId" json:"parentSpanId,omitempty"`
	RequestId    string          `protobuf:"bytes,4,opt,name=requestId" json:"requestId,omitempty"`
	EventType    Event_EventType `protobuf:"varint,5,opt,name=eventType,enum=inkah.Event_EventType" json:"eventType,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Event) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *Event) GetParentSpanId() string {
	if m != nil {
		return m.ParentSpanId
	}
	return ""
}

func (m *Event) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Event) GetEventType() Event_EventType {
	if m != nil {
		return m.EventType
	}
	return Event_SPAN_BEGIN
}

type EventResponse struct {
}

func (m *EventResponse) Reset()                    { *m = EventResponse{} }
func (m *EventResponse) String() string            { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()               {}
func (*EventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Event)(nil), "inkah.Event")
	proto.RegisterType((*EventResponse)(nil), "inkah.EventResponse")
	proto.RegisterEnum("inkah.Event_EventType", Event_EventType_name, Event_EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Inkah service

type InkahClient interface {
	RegisterEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventResponse, error)
}

type inkahClient struct {
	cc *grpc.ClientConn
}

func NewInkahClient(cc *grpc.ClientConn) InkahClient {
	return &inkahClient{cc}
}

func (c *inkahClient) RegisterEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := grpc.Invoke(ctx, "/inkah.Inkah/RegisterEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Inkah service

type InkahServer interface {
	RegisterEvent(context.Context, *Event) (*EventResponse, error)
}

func RegisterInkahServer(s *grpc.Server, srv InkahServer) {
	s.RegisterService(&_Inkah_serviceDesc, srv)
}

func _Inkah_RegisterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InkahServer).RegisterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inkah.Inkah/RegisterEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InkahServer).RegisterEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inkah_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inkah.Inkah",
	HandlerType: (*InkahServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterEvent",
			Handler:    _Inkah_RegisterEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x9b, 0xd4, 0xd4, 0xe6, 0x35, 0x69, 0xeb, 0x43, 0x4a, 0x10, 0x87, 0x92, 0xa9, 0x53,
	0x86, 0xaa, 0xab, 0x60, 0x31, 0x48, 0x06, 0x83, 0x26, 0x75, 0x71, 0x91, 0xd4, 0x3c, 0xb5, 0x08,
	0x97, 0xf3, 0xee, 0x2a, 0xb8, 0xf9, 0xa7, 0x4b, 0x5e, 0x1a, 0xdb, 0x2e, 0xc7, 0x7d, 0x7f, 0xdc,
	0xf1, 0xe1, 0x0b, 0x03, 0xfa, 0x26, 0x61, 0x22, 0xa9, 0x2a, 0x53, 0xa1, 0xb3, 0x16, 0x9f, 0xc5,
	0x47, 0xf8, 0x6b, 0x83, 0x13, 0xd7, 0x36, 0x06, 0x70, 0x6c, 0x54, 0xf1, 0x4a, 0x49, 0x19, 0x58,
	0x53, 0x6b, 0xe6, 0x66, 0xad, 0xc4, 0x09, 0xf4, 0xb4, 0x2c, 0x44, 0x52, 0x06, 0x36, 0x07, 0x5b,
	0x85, 0x21, 0x78, 0xb2, 0x50, 0x24, 0x4c, 0xde, 0xa4, 0x5d, 0x4e, 0x0f, 0x3c, 0x3c, 0x07, 0x57,
	0xd1, 0xd7, 0x86, 0xb4, 0x49, 0xca, 0xe0, 0x88, 0x0b, 0x3b, 0x03, 0x2f, 0xc1, 0x65, 0xa6, 0xe5,
	0x8f, 0xa4, 0xc0, 0x99, 0x5a, 0xb3, 0xe1, 0x7c, 0x12, 0x31, 0x58, 0xc4, 0x50, 0xcd, 0x59, 0xa7,
	0xd9, 0xae, 0x18, 0xde, 0x83, 0xfb, 0xef, 0xe3, 0x10, 0x20, 0x7f, 0xb8, 0x49, 0x5f, 0x16, 0xf1,
	0x5d, 0x92, 0x8e, 0x3b, 0xe8, 0x41, 0x9f, 0x75, 0x9c, 0xde, 0x8e, 0x2d, 0x3c, 0x01, 0x3f, 0x8b,
	0x1f, 0x9f, 0xe2, 0x7c, 0xb9, 0x2d, 0xd8, 0x38, 0x82, 0x41, 0x6b, 0xd5, 0x9d, 0x6e, 0x38, 0x02,
	0x9f, 0xbf, 0xcb, 0x48, 0xcb, 0x4a, 0x68, 0x9a, 0x5f, 0x83, 0x93, 0xd4, 0x0c, 0x78, 0x05, 0x7e,
	0x46, 0xef, 0x6b, 0x6d, 0x48, 0x35, 0x1b, 0x79, 0xfb, 0x70, 0x67, 0xa7, 0xfb, 0xaa, 0x7d, 0x1d,
	0x76, 0x16, 0xf0, 0xdc, 0xe7, 0x8d, 0x57, 0x9b, 0xb7, 0x55, 0x8f, 0x6f, 0x17, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x7b, 0x2d, 0xc9, 0x28, 0x7c, 0x01, 0x00, 0x00,
}
